### PR TITLE
Resolved issue of rewriting URL string in each service

### PR DESCRIPTION
**Pull request by mbaugus**
Added the variable ```serverURL``` to environment.

It's now set to 'http://localhost:54154/', which should be the default for Visual Studio, and was already set tot his by the original project owners.

Because of the dependency on the environment, when a production version of the front-end is run, the environment.prod.ts file must also have a serverURL definition with the appropriate address to use.  I left it alone since Greg will be the one handling that.

### CODE REVIEW

**Review by gpdoud — CHANGES_REQUESTED** [review]
Your changes do what the issue requested, but I left out one requirement that I will add to the issue. It is that the change on the URL must be possible at deployment time. It cannot be done in code because the code will not be available at installation time. Plus we won't know the URL until the customer sets it up. I'll add more detail to the issue, but we can't do it this way.

**Comment by mbaugus** [comment]
Okay sounds good.  I'm going to make another branch/pull request for it.

**Comment by gpdoud** [comment]
Did you close this issue?

**Comment by mbaugus** [comment]
Ya i wasn't sure proper procedure since I wanted to start a new branch

**Pull request closed without merging**
